.TH "dnsi-lookup" "1" "NLnet Labs"

.SH NAME
dnsi-lookup - Look up a host or address

.SH SYNOPSIS
.B dnsi lookup
[\fIoptions\fR]
.I host_or_addr

.SH DESCRIPTION
The
.B dnsi lookup
command looks up the given hosts and address, does a corresponding forward or
reverse lookup and prints the results.

.SH OPTIONS
.TP
.BR -h ,\  --help
Print help information.
