.TH "dnsi" "1" "NLnet Labs"

.SH NAME
dnsi - inspect the DNS

.SH SYNOPSIS
.B dnsi
[<options>]
<command>
[<args>]

.SH DESCRIPTION
Inspect the Domain Name System (DNS) in various ways.

.B dnsi
provides a number of commands that perform various tasks related to the DNS.

Please consult the manual pages for these individual commands for more
information.

.SH IDNS COMMANDS

.PP
\fBdnsi-query\fR(1)
.RS 4
Send a query to a name server.
